[build]
  publish = "build"
  functions = "netlify/functions"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "build"
  functionsPort = 9999
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 